/*
 * Copyright (c) 2024.  Jan Eike Suchard. All rights reserved
 * SPDX-License-Identifier: MIT
 */

package types

import "github.com/jackc/pgx/v5/pgtype"

type Sale struct {
	// ID contains the sale id which identifies this sale throughout the
	// application
	ID pgtype.UUID `json:"id" db:"id"`

	// At contains the timestamp that displays when the sale happened
	At pgtype.Timestamptz `json:"at" db:"at"`

	// Amount contains the total amount the sale has been for
	Amount pgtype.Numeric `json:"amount" db:"amount"`

	// Items is an array with the Item.ID of known items.
	Items []pgtype.UUID `json:"items" db:"items"`

	// CustomItems contains a list of Item entries which have
	// been created locally on the user devices and are stored for having a
	// complete transaction state
	CustomItems []Item `json:"customItems" db:"custom_items"`

	// CardPaymentId contains the id generated by the card transaction backend
	// used in the frontend
	CardPaymentId pgtype.Text `json:"cardPaymentId" db:"card_payment_id"`

	// Refunded indicates if this sale has been refunded
	Refunded bool `json:"refunded" db:"refunded"`
}
